language: node_js

node_js:
  - "10"

cache: yarn

stages:
  - lint
  - test

jobs:
  include:
    - stage: "lint"
      name: "Check lint"
      script:
        - yarn run eslint ./
    - stage: "test"
      name: "Running tests"
      script:
        - yarn test --no-watch 
