export enum Constants {
  SET_CURRENT_TAB = "set-current-tab",
  ADD_POSTS = "add-posts",
  REMOVE_POST = "remove-post",
  ADD_ACCOUNTS = "add-accounts",
  ADD_ACCOUNT = "add-account",
  REMOVE_ACCOUNT = "remove-account",
  ADD_IMAGES = "add-images",
  REMOVE_IMAGE = "remove-image",
  SET_UPLOAD_MESSAGE = "set-upload-message",
  SET_FILE = "set-file",
  START_UPLOADING = "start-uploading",
  END_UPLOADING = "end-uploading",
  UPDATE_USER = "update-user",
  RESET_SELECTED = "reset-selected",
  SET_SELECT_MODE = "set-select-mode",
  REMOVE_SELECTED = "remove-selected",
  ADD_SELECTED = "add-selected",
  LOADING = "loading",
  NOT_LOADING = "not-loading",
}
