name = "wiggles-api"
main = "src/index.ts"
compatibility_date = "2022-09-11"

route = { pattern = "wiggle-room.xyz/api/*", zone_name = "wiggle-room.xyz" }

[vars]
AUDIENCE = "26b6452e75e854fb6f37cc5deccc0a1897e5160e7f4f3d6e52eabf31cc8b0726"
DOMAIN = "https://johnpangalos.cloudflareaccess.com"
ENV = "production"

[[kv_namespaces]]
  binding = "WIGGLES"
  id = "a6c8694133f14020808088b6c53300a8"
  preview_id = "a6c8694133f14020808088b6c53300a8"


