name: Deploy Web
on: 
  push:
    branches:
      - main
    paths:
      - 'web/**'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    name: Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        uses: ./.github/actions/install-deps

      - name: Build
        run: cd web && VITE_RELEASE=${{ env.GITHUB_SHA }} pnpm build

      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: e5933c765c57d2f3a58d86973c88362c
          projectName: wiggles
          directory: web/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          environment: production


      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
          sourcemaps: ./web/dist
          ignore_missing: true
          ignore_empty: true
